// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQCWZomcCnKQBtbU-TgO_18OX-Np2X8nc',
    appId: '1:161217649054:web:ade308c66aeb844bca1e8f',
    messagingSenderId: '161217649054',
    projectId: 'plated-hash-405713',
    authDomain: 'plated-hash-405713.firebaseapp.com',
    storageBucket: 'plated-hash-405713.appspot.com',
    measurementId: 'G-74RMHG8NL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIj0UonVUg4zIOMx2PEZlfhxmAqpNyJ_o',
    appId: '1:161217649054:android:d53af40de5722dd2ca1e8f',
    messagingSenderId: '161217649054',
    projectId: 'plated-hash-405713',
    storageBucket: 'plated-hash-405713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYX5agCaH5HovYdO7X38klB8gtx0KC7no',
    appId: '1:161217649054:ios:025190e61b927ef3ca1e8f',
    messagingSenderId: '161217649054',
    projectId: 'plated-hash-405713',
    storageBucket: 'plated-hash-405713.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYX5agCaH5HovYdO7X38klB8gtx0KC7no',
    appId: '1:161217649054:ios:025190e61b927ef3ca1e8f',
    messagingSenderId: '161217649054',
    projectId: 'plated-hash-405713',
    storageBucket: 'plated-hash-405713.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQCWZomcCnKQBtbU-TgO_18OX-Np2X8nc',
    appId: '1:161217649054:web:2d366d58319f0a16ca1e8f',
    messagingSenderId: '161217649054',
    projectId: 'plated-hash-405713',
    authDomain: 'plated-hash-405713.firebaseapp.com',
    storageBucket: 'plated-hash-405713.appspot.com',
    measurementId: 'G-FB1F6HNZVS',
  );

}